# Generated by Django 5.1.4 on 2025-01-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0003_alter_candidate_email_alter_candidate_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
    ]
